# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:/fluentWidgetProject/DeepMiner/app/ui/chartPlotPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets


class Ui_chartPlotPage(object):
    def setupUi(self, chartPlotPage):
        chartPlotPage.setObjectName("chartPlotPage")
        chartPlotPage.resize(894, 500)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(chartPlotPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CardWidget = CardWidget(chartPlotPage)
        self.CardWidget.setBorderRadius(30)
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LargeTitleLabel = LargeTitleLabel(self.CardWidget)
        self.LargeTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.verticalLayout.addWidget(self.LargeTitleLabel)
        self.chartPlotImageLabel = ImageLabel(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chartPlotImageLabel.sizePolicy().hasHeightForWidth())
        self.chartPlotImageLabel.setSizePolicy(sizePolicy)
        self.chartPlotImageLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chartPlotImageLabel.setObjectName("chartPlotImageLabel")
        self.verticalLayout.addWidget(self.chartPlotImageLabel)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.CardWidget)

        self.retranslateUi(chartPlotPage)
        QtCore.QMetaObject.connectSlotsByName(chartPlotPage)

    def retranslateUi(self, chartPlotPage):
        _translate = QtCore.QCoreApplication.translate
        chartPlotPage.setWindowTitle(_translate("chartPlotPage", "Form"))
        self.LargeTitleLabel.setText(_translate("chartPlotPage", "TestChartPlot Laebel"))


from qfluentwidgets import CardWidget, ImageLabel, LargeTitleLabel
